
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - Releases Workflow

    on:
      workflow_dispatch:
        inputs:
          job_to_run:
            description: 'Select the job to run manually'
            required: true
            default: 'promote'

    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/release.yml@main
        with:
          job_to_run: ${{ inputs.job_to_run }}
          data_project_dir: v3/quarentine_v3
          tb_deploy: true
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_QUARENTINE_V3 }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
